apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: acm-unstructured-example
  sourceFormat: unstructured  # this is the param that switches the repo format
  git:
    secretType: ssh
    syncRepo: git@github.com:linde/acm-unstructured-minimal.git
    policyDir: config-root



